import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { BackgroundGrid } from "@/components/background-grid";
import { Blobs } from "@/components/blob";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio | Shahriar Hossen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#0f172a] text-gray-100`}>
        <BackgroundGrid>
          <Blobs />
          <Navbar />
          {children}
        </BackgroundGrid>
      </body>
    </html>
  );
}
